export type ScenicIconKind =
  | "airport"
  | "city"
  | "forest"
  | "lake"
  | "mountain"
  | "village"
  | "oilfield"
  | "meadow";

export type RoadClass = "高速" | "国道" | "省道" | "乡道" | "牧道";

export type AltayMapNode = {
  id: string;
  name: string;
  icon: ScenicIconKind;
  elevationM: number;
  x: number;
  y: number;
  labelX: number;
  labelY: number;
  summary: string;
  lat: number;
  lng: number;
};

export type AltaySegment = {
  id: string;
  fromId: string;
  toId: string;
  distanceKm: number;
  driveHours: number;
  walkHours: number;
  roadClass: RoadClass;
  surface: "沥青" | "水泥" | "砂石" | "土路";
  maxGradePct: number;
  climateAdvice: string;
  supply: string;
  signal: string;
  special: string;
  seasonal: string;
  note: string;
  path: string;
};

export type AltayRouteOption = {
  id: string;
  label: string;
  isMain: boolean;
  summary: string;
  segmentIds: string[];
};

export type AltayRoutePlan = {
  destinationId: string;
  options: AltayRouteOption[];
};

export const DEFAULT_ROUTE_ORIGIN_ID = "altay-city";

export const ALTAI_MAP_NODES: AltayMapNode[] = [
  {
    id: "altay-airport",
    name: "阿勒泰机场",
    icon: "airport",
    elevationM: 739,
    x: 82,
    y: 92,
    labelX: 79,
    labelY: 98,
    summary: "入疆门户，租车和补给效率最高，适合作为全线起落点。",
    lat: 47.749,
    lng: 88.085,
  },
  {
    id: "altay-city",
    name: "阿勒泰市",
    icon: "city",
    elevationM: 760,
    x: 79,
    y: 61,
    labelX: 85,
    labelY: 58,
    summary: "默认起点，城市补给成熟，适合首晚落脚和整备。",
    lat: 47.848,
    lng: 88.132,
  },
  {
    id: "koktokay",
    name: "可可托海",
    icon: "mountain",
    elevationM: 1250,
    x: 70,
    y: 74,
    labelX: 78,
    labelY: 70,
    summary: "峡谷和额尔齐斯河谷景观核心点，盘山路比例较高。",
    lat: 46.992,
    lng: 89.513,
  },
  {
    id: "burqin",
    name: "布尔津",
    icon: "village",
    elevationM: 480,
    x: 57,
    y: 41,
    labelX: 63,
    labelY: 38,
    summary: "喀纳斯门户县城，夜市、住宿和加油站密集。",
    lat: 48.061,
    lng: 86.865,
  },
  {
    id: "kanas",
    name: "喀纳斯",
    icon: "lake",
    elevationM: 1374,
    x: 69,
    y: 18,
    labelX: 64,
    labelY: 12,
    summary: "高山湖泊核心景区，景区公路弯急，旺季限流明显。",
    lat: 48.703,
    lng: 87.038,
  },
  {
    id: "kanas-depth",
    name: "喀纳斯深度游",
    icon: "lake",
    elevationM: 1455,
    x: 84,
    y: 24,
    labelX: 91,
    labelY: 22,
    summary: "围绕观鱼台与湖湾慢游的延展段，适合半日深度停留。",
    lat: 48.748,
    lng: 87.169,
  },
  {
    id: "hemu",
    name: "禾木",
    icon: "forest",
    elevationM: 1124,
    x: 42,
    y: 41,
    labelX: 34,
    labelY: 36,
    summary: "晨雾和木屋村落最具代表性，但晨间路面湿滑、弯道多。",
    lat: 48.586,
    lng: 87.446,
  },
  {
    id: "karamay",
    name: "克拉玛依",
    icon: "oilfield",
    elevationM: 420,
    x: 48,
    y: 63,
    labelX: 43,
    labelY: 67,
    summary: "戈壁转场核心节点，油料、维修和住宿条件稳定。",
    lat: 45.595,
    lng: 84.873,
  },
  {
    id: "sailimu",
    name: "赛里木湖",
    icon: "lake",
    elevationM: 2071,
    x: 51,
    y: 79,
    labelX: 45,
    labelY: 83,
    summary: "高海拔湖区，风大温差大，是西段最稳定的观景点之一。",
    lat: 44.602,
    lng: 81.153,
  },
  {
    id: "yining",
    name: "伊宁",
    icon: "city",
    elevationM: 663,
    x: 19,
    y: 84,
    labelX: 13,
    labelY: 88,
    summary: "伊犁河谷主要城市节点，补给最完整，适合住宿和收尾。",
    lat: 43.916,
    lng: 81.315,
  },
  {
    id: "nalati",
    name: "那拉提",
    icon: "meadow",
    elevationM: 1540,
    x: 41,
    y: 95,
    labelX: 48,
    labelY: 97,
    summary: "草原谷地段景观优秀，但天气对通行体验影响较大。",
    lat: 43.289,
    lng: 84.058,
  },
  {
    id: "yining-airport",
    name: "伊宁机场",
    icon: "airport",
    elevationM: 676,
    x: 17,
    y: 98,
    labelX: 10,
    labelY: 103,
    summary: "终点机场，适合归还车辆后离疆，建议至少提前 90 分钟到达。",
    lat: 43.958,
    lng: 81.331,
  },
];

export const ALTAI_MAP_SEGMENTS: AltaySegment[] = [
  {
    id: "city-airport-main",
    fromId: "altay-city",
    toId: "altay-airport",
    distanceKm: 18.6,
    driveHours: 0.4,
    walkHours: 4.8,
    roadClass: "高速",
    surface: "沥青",
    maxGradePct: 2.5,
    climateAdvice: "冬季凌晨有结冰风险，建议预留刹停距离。",
    supply: "市区加油站和机场快充点都较近。",
    signal: "4G/5G 覆盖稳定。",
    special: "机场快速路，进场高峰主要出现在早班机时段。",
    seasonal: "雪季除冰及时，暴雪天可能短时限速。",
    note: "最稳妥的接驳段，适合落地直接进市区。",
    path: "M 78 90 C 79 84, 80 72, 79 61",
  },
  {
    id: "city-airport-alt",
    fromId: "altay-city",
    toId: "altay-airport",
    distanceKm: 20.4,
    driveHours: 0.5,
    walkHours: 5.2,
    roadClass: "国道",
    surface: "沥青",
    maxGradePct: 3.2,
    climateAdvice: "遇大风时城市外环段体感更明显。",
    supply: "外环补给点少于主线，适合白天通行。",
    signal: "全线信号稳定。",
    special: "绕行城市外缘，可避开中心城区短时拥堵。",
    seasonal: "雨雪天弯道抓地力下降较明显。",
    note: "适合高峰期避开市区红绿灯。",
    path: "M 80 89 C 74 84, 74 68, 79 61",
  },
  {
    id: "city-kok-main",
    fromId: "altay-city",
    toId: "koktokay",
    distanceKm: 311.4,
    driveHours: 4.6,
    walkHours: 62,
    roadClass: "国道",
    surface: "沥青",
    maxGradePct: 5.8,
    climateAdvice: "春末风沙较重，建议白天通行。",
    supply: "富蕴一线补给成熟，沿线加油点相对稳定。",
    signal: "城镇段稳定，峡谷口偶有弱网。",
    special: "进山后有连续长弯和观景停车带。",
    seasonal: "雨季局部有落石风险，雪季限速明显。",
    note: "阿勒泰到可可托海的主推荐线。",
    path: "M 78 61 C 75 66, 72 69, 70 74",
  },
  {
    id: "city-kok-alt",
    fromId: "altay-city",
    toId: "koktokay",
    distanceKm: 327.8,
    driveHours: 5.1,
    walkHours: 66,
    roadClass: "省道",
    surface: "沥青",
    maxGradePct: 6.4,
    climateAdvice: "秋季晨雾较重，建议推迟进山时间。",
    supply: "补给点较主线少，离开市区前建议满油。",
    signal: "中段断续，导航需提前缓存。",
    special: "风景更完整，但县道并入省道段会更慢。",
    seasonal: "雨后个别会车点会积水。",
    note: "适合偏好慢游和沿途观景。",
    path: "M 80 61 C 76 68, 73 71, 68 75",
  },
  {
    id: "kok-burqin-main",
    fromId: "koktokay",
    toId: "burqin",
    distanceKm: 286.3,
    driveHours: 4.8,
    walkHours: 58,
    roadClass: "省道",
    surface: "沥青",
    maxGradePct: 7.2,
    climateAdvice: "雨后易出现泥水带，需控制入弯速度。",
    supply: "青河和冲乎尔可补油补水。",
    signal: "河谷段 4G 断续，县城段稳定。",
    special: "峡谷转丘陵路形变化大，注意连续弯。",
    seasonal: "春汛和秋末结冰期均需谨慎。",
    note: "连接可可托海与布尔津的标准转场线。",
    path: "M 68 73 C 63 65, 60 54, 57 41",
  },
  {
    id: "kok-burqin-alt",
    fromId: "koktokay",
    toId: "burqin",
    distanceKm: 301.2,
    driveHours: 5.3,
    walkHours: 61,
    roadClass: "乡道",
    surface: "水泥",
    maxGradePct: 8.4,
    climateAdvice: "雨雪天不建议夜间通行。",
    supply: "补给点较少，建议携带应急饮水。",
    signal: "弱网区更长。",
    special: "路形更曲折，但车流较少。",
    seasonal: "积雪期可能临时封闭部分支路。",
    note: "备用慢行线，适合错峰避车。",
    path: "M 69 74 C 62 66, 59 57, 55 42",
  },
  {
    id: "burqin-kanas-main",
    fromId: "burqin",
    toId: "kanas",
    distanceKm: 154.9,
    driveHours: 2.9,
    walkHours: 36,
    roadClass: "省道",
    surface: "沥青",
    maxGradePct: 8.9,
    climateAdvice: "景区晨间低云多，刹车要更柔和。",
    supply: "贾登峪前补给完善，进景区后补给价格偏高。",
    signal: "贾登峪前稳定，景区后半段断续。",
    special: "盘山公路为主，部分回头弯半径较小。",
    seasonal: "雪季可能单向放行，旺季易排队。",
    note: "布尔津进喀纳斯的标准主线。",
    path: "M 57 41 C 59 34, 63 24, 69 18",
  },
  {
    id: "burqin-kanas-alt",
    fromId: "burqin",
    toId: "kanas",
    distanceKm: 166.8,
    driveHours: 3.3,
    walkHours: 39,
    roadClass: "乡道",
    surface: "水泥",
    maxGradePct: 10.5,
    climateAdvice: "雨天和融雪期更考验抓地力。",
    supply: "需在布尔津补齐物资后再出发。",
    signal: "山谷段信号更弱。",
    special: "适合错峰但路窄弯急，不建议新手夜驾。",
    seasonal: "积雪期不稳定，存在临时封控。",
    note: "备用观景线，节假日可避开主线拥堵。",
    path: "M 55 42 C 58 31, 62 22, 68 17",
  },
  {
    id: "kanas-depth-main",
    fromId: "kanas",
    toId: "kanas-depth",
    distanceKm: 28.4,
    driveHours: 0.8,
    walkHours: 6.5,
    roadClass: "乡道",
    surface: "沥青",
    maxGradePct: 9.6,
    climateAdvice: "午后天气变化快，山顶风大。",
    supply: "景区服务点密度一般，以热饮和简餐为主。",
    signal: "局部高点信号稳定，湖湾段弱。",
    special: "观鱼台与湖湾慢游段，步行和摆渡占比更高。",
    seasonal: "旺季摆渡等待时间会明显增加。",
    note: "喀纳斯核心深度游延展段。",
    path: "M 69 18 C 73 19, 79 21, 84 24",
  },
  {
    id: "burqin-hemu-main",
    fromId: "burqin",
    toId: "hemu",
    distanceKm: 141.2,
    driveHours: 3.1,
    walkHours: 34,
    roadClass: "省道",
    surface: "沥青",
    maxGradePct: 9.2,
    climateAdvice: "晨间雾气重，建议天亮后再发车。",
    supply: "冲乎尔可作为中途补给点。",
    signal: "入村前后弱网，导航需缓存。",
    special: "连续山路，部分路肩狭窄，会车需减速礼让。",
    seasonal: "秋末到春初常见薄冰。",
    note: "布尔津至禾木的主线公路。",
    path: "M 56 41 C 51 40, 46 40, 42 41",
  },
  {
    id: "burqin-hemu-alt",
    fromId: "burqin",
    toId: "hemu",
    distanceKm: 147.9,
    driveHours: 3.5,
    walkHours: 36,
    roadClass: "乡道",
    surface: "水泥",
    maxGradePct: 10.3,
    climateAdvice: "雨后局部有泥水和落叶湿滑。",
    supply: "补给密度略低于主线。",
    signal: "弱网段更长。",
    special: "更贴近山谷，景观更好但转弯更密。",
    seasonal: "雨雪期不建议夜间行驶。",
    note: "慢游备用线。",
    path: "M 57 42 C 51 43, 46 44, 40 42",
  },
  {
    id: "hemu-karamay-main",
    fromId: "hemu",
    toId: "karamay",
    distanceKm: 472.1,
    driveHours: 6.5,
    walkHours: 98,
    roadClass: "国道",
    surface: "沥青",
    maxGradePct: 6.6,
    climateAdvice: "中午横风和午后暴晒最明显。",
    supply: "布尔津出发前加满油最稳妥。",
    signal: "县城和服务区正常，戈壁段断续。",
    special: "从山地过渡到戈壁，路幅开阔但连续驾驶疲劳大。",
    seasonal: "风沙季能见度可能骤降。",
    note: "禾木转出北线后进入大西段的主路线。",
    path: "M 42 41 C 41 52, 41 59, 48 63",
  },
  {
    id: "hemu-karamay-alt",
    fromId: "hemu",
    toId: "karamay",
    distanceKm: 498.7,
    driveHours: 7.1,
    walkHours: 104,
    roadClass: "省道",
    surface: "沥青",
    maxGradePct: 7.4,
    climateAdvice: "更容易遇到侧风与沙尘。",
    supply: "县镇补给可用，但间隔更长。",
    signal: "主线外段存在弱网区。",
    special: "绕行乌尔禾段景观更足，但耗时增加。",
    seasonal: "风沙季建议白天通行。",
    note: "景观增强的备用线。",
    path: "M 41 41 C 38 55, 42 62, 47 64",
  },
  {
    id: "karamay-sailimu-main",
    fromId: "karamay",
    toId: "sailimu",
    distanceKm: 423.6,
    driveHours: 5.6,
    walkHours: 86,
    roadClass: "高速",
    surface: "沥青",
    maxGradePct: 4.2,
    climateAdvice: "果子沟山口阵风强，需要注意横风修正。",
    supply: "乌苏、精河补给成熟。",
    signal: "高速全程信号较稳。",
    special: "高速占比高，桥隧组合路段多。",
    seasonal: "大风和雨雪时可能阶段性限速。",
    note: "克拉玛依到赛里木湖的效率主线。",
    path: "M 48 63 C 50 70, 50 75, 51 79",
  },
  {
    id: "karamay-sailimu-alt",
    fromId: "karamay",
    toId: "sailimu",
    distanceKm: 451.8,
    driveHours: 6.3,
    walkHours: 92,
    roadClass: "国道",
    surface: "沥青",
    maxGradePct: 5.6,
    climateAdvice: "雨季路肩积水更明显。",
    supply: "可在精河补给，间隔略长于高速主线。",
    signal: "城镇段正常，部分国道段弱网。",
    special: "国道观景更完整，但通行效率低于高速。",
    seasonal: "旅游旺季货车与自驾车混流明显。",
    note: "适合不赶路、想多看戈壁地貌。",
    path: "M 47 64 C 45 71, 47 77, 50 80",
  },
  {
    id: "sailimu-yining-main",
    fromId: "sailimu",
    toId: "yining",
    distanceKm: 150.8,
    driveHours: 2.3,
    walkHours: 32,
    roadClass: "高速",
    surface: "沥青",
    maxGradePct: 5.1,
    climateAdvice: "湖区出发温差大，建议先热车。",
    supply: "果子沟和伊宁前补给方便。",
    signal: "全线信号稳定。",
    special: "果子沟桥隧段景观最佳，但大风天需控速。",
    seasonal: "节假日景区口和桥隧段易排队。",
    note: "赛里木湖至伊宁的标准主线。",
    path: "M 50 79 C 40 77, 28 80, 19 84",
  },
  {
    id: "sailimu-yining-alt",
    fromId: "sailimu",
    toId: "yining",
    distanceKm: 163.4,
    driveHours: 2.8,
    walkHours: 35,
    roadClass: "国道",
    surface: "沥青",
    maxGradePct: 6.2,
    climateAdvice: "雨天和团雾时更需注意跟车距离。",
    supply: "沿线乡镇补给可用，但不如主线集中。",
    signal: "大部分路段稳定。",
    special: "可避开高速拥堵，适合错峰。",
    seasonal: "旅游季车流略杂，进城口更慢。",
    note: "赛里木湖返伊宁的备用通勤线。",
    path: "M 52 80 C 39 83, 26 85, 20 85",
  },
  {
    id: "yining-nalati-main",
    fromId: "yining",
    toId: "nalati",
    distanceKm: 262.3,
    driveHours: 4.1,
    walkHours: 58,
    roadClass: "国道",
    surface: "沥青",
    maxGradePct: 6.8,
    climateAdvice: "午后对流天气会影响草原段视距。",
    supply: "新源沿线补给成熟。",
    signal: "河谷段信号稳定，山口轻微弱网。",
    special: "谷地平缓后转草原爬升，风景层次明显。",
    seasonal: "旺季景区附近排队时间较长。",
    note: "伊宁到那拉提的经典草原线。",
    path: "M 19 84 C 24 89, 31 93, 41 95",
  },
  {
    id: "yining-nalati-alt",
    fromId: "yining",
    toId: "nalati",
    distanceKm: 278.6,
    driveHours: 4.6,
    walkHours: 61,
    roadClass: "省道",
    surface: "水泥",
    maxGradePct: 7.6,
    climateAdvice: "雨季路肩泥水较多。",
    supply: "补给点略少，适合白天慢行。",
    signal: "谷地正常，支线村镇周边弱网。",
    special: "车少更安静，但会牺牲一部分效率。",
    seasonal: "初春融雪可能影响局部会车。",
    note: "那拉提备用慢行线。",
    path: "M 18 85 C 23 92, 30 95, 41 96",
  },
  {
    id: "nalati-airport-main",
    fromId: "nalati",
    toId: "yining-airport",
    distanceKm: 287.4,
    driveHours: 4.2,
    walkHours: 64,
    roadClass: "国道",
    surface: "沥青",
    maxGradePct: 6.4,
    climateAdvice: "返程易遇西晒和侧风，建议预留缓冲时间。",
    supply: "新源、伊宁沿线补给完整。",
    signal: "全程基本稳定。",
    special: "草原回城后接机场快速路，节奏变化较快。",
    seasonal: "旅游季和节假日返城晚高峰更慢。",
    note: "完成那拉提段后直达机场的主路线。",
    path: "M 41 95 C 34 99, 25 100, 17 98",
  },
  {
    id: "nalati-airport-alt",
    fromId: "nalati",
    toId: "yining-airport",
    distanceKm: 301.1,
    driveHours: 4.8,
    walkHours: 67,
    roadClass: "省道",
    surface: "水泥",
    maxGradePct: 7.2,
    climateAdvice: "雨后局部会有湿滑阴坡。",
    supply: "沿线县镇补给可用，但节奏更慢。",
    signal: "支线进入城区前会短时弱网。",
    special: "绕行乡镇，可避开主线高峰。",
    seasonal: "积雪期和大雨天不建议赶航班走这条。",
    note: "适合不赶时间的慢返程。",
    path: "M 42 96 C 34 101, 24 102, 16 99",
  },
];

export const ALTAI_ROUTE_PLANS: AltayRoutePlan[] = [
  {
    destinationId: "altay-airport",
    options: [
      { id: "plan-airport-main", label: "主路线 · 机场快线", isMain: true, summary: "最快接驳机场，适合落地或离疆。", segmentIds: ["city-airport-main"] },
      { id: "plan-airport-alt", label: "备选 · 城市外环", isMain: false, summary: "避开市区高峰，整体更稳。", segmentIds: ["city-airport-alt"] },
    ],
  },
  {
    destinationId: "koktokay",
    options: [
      { id: "plan-kok-main", label: "主路线 · 富蕴峡谷线", isMain: true, summary: "效率和景观平衡最佳。", segmentIds: ["city-kok-main"] },
      { id: "plan-kok-alt", label: "备选 · 慢游省道线", isMain: false, summary: "更适合白天观景，通行更慢。", segmentIds: ["city-kok-alt"] },
    ],
  },
  {
    destinationId: "burqin",
    options: [
      { id: "plan-burqin-main", label: "主路线 · 可可托海转场", isMain: true, summary: "先到可可托海，再转布尔津。", segmentIds: ["city-kok-main", "kok-burqin-main"] },
      { id: "plan-burqin-alt", label: "备选 · 双慢线", isMain: false, summary: "避开主线车流，适合慢游。", segmentIds: ["city-kok-alt", "kok-burqin-alt"] },
    ],
  },
  {
    destinationId: "kanas",
    options: [
      { id: "plan-kanas-main", label: "主路线 · 标准入湖线", isMain: true, summary: "阿勒泰经可可托海、布尔津进入喀纳斯。", segmentIds: ["city-kok-main", "kok-burqin-main", "burqin-kanas-main"] },
      { id: "plan-kanas-alt", label: "备选 · 错峰观景线", isMain: false, summary: "以备用山路切入，适合错峰。", segmentIds: ["city-kok-alt", "kok-burqin-alt", "burqin-kanas-alt"] },
    ],
  },
  {
    destinationId: "kanas-depth",
    options: [
      { id: "plan-kanas-depth-main", label: "主路线 · 深度游主线", isMain: true, summary: "进入喀纳斯后继续去观鱼台与湖湾。", segmentIds: ["city-kok-main", "kok-burqin-main", "burqin-kanas-main", "kanas-depth-main"] },
      { id: "plan-kanas-depth-alt", label: "备选 · 深度游慢线", isMain: false, summary: "整体更慢，但适合避高峰。", segmentIds: ["city-kok-alt", "kok-burqin-alt", "burqin-kanas-alt", "kanas-depth-main"] },
    ],
  },
  {
    destinationId: "hemu",
    options: [
      { id: "plan-hemu-main", label: "主路线 · 布禾主线", isMain: true, summary: "从布尔津切入禾木，适合首次自驾。", segmentIds: ["city-kok-main", "kok-burqin-main", "burqin-hemu-main"] },
      { id: "plan-hemu-alt", label: "备选 · 山谷慢行线", isMain: false, summary: "景观更完整，但会慢一些。", segmentIds: ["city-kok-alt", "kok-burqin-alt", "burqin-hemu-alt"] },
    ],
  },
  {
    destinationId: "karamay",
    options: [
      { id: "plan-karamay-main", label: "主路线 · 禾木南下线", isMain: true, summary: "经禾木转入戈壁路段。", segmentIds: ["city-kok-main", "kok-burqin-main", "burqin-hemu-main", "hemu-karamay-main"] },
      { id: "plan-karamay-alt", label: "备选 · 乌尔禾观景线", isMain: false, summary: "景观更丰富，适合不赶路。", segmentIds: ["city-kok-alt", "kok-burqin-alt", "burqin-hemu-alt", "hemu-karamay-alt"] },
    ],
  },
  {
    destinationId: "sailimu",
    options: [
      { id: "plan-sailimu-main", label: "主路线 · 高速收口线", isMain: true, summary: "克拉玛依后走效率主线直抵赛里木湖。", segmentIds: ["city-kok-main", "kok-burqin-main", "burqin-hemu-main", "hemu-karamay-main", "karamay-sailimu-main"] },
      { id: "plan-sailimu-alt", label: "备选 · 戈壁慢游线", isMain: false, summary: "国道景观更完整，但更耗时。", segmentIds: ["city-kok-alt", "kok-burqin-alt", "burqin-hemu-alt", "hemu-karamay-alt", "karamay-sailimu-alt"] },
    ],
  },
  {
    destinationId: "yining",
    options: [
      { id: "plan-yining-main", label: "主路线 · 果子沟主线", isMain: true, summary: "赛里木湖后经果子沟进入伊宁。", segmentIds: ["city-kok-main", "kok-burqin-main", "burqin-hemu-main", "hemu-karamay-main", "karamay-sailimu-main", "sailimu-yining-main"] },
      { id: "plan-yining-alt", label: "备选 · 国道进城线", isMain: false, summary: "绕开高速高峰，通行更平缓。", segmentIds: ["city-kok-alt", "kok-burqin-alt", "burqin-hemu-alt", "hemu-karamay-alt", "karamay-sailimu-alt", "sailimu-yining-alt"] },
    ],
  },
  {
    destinationId: "nalati",
    options: [
      { id: "plan-nalati-main", label: "主路线 · 草原主线", isMain: true, summary: "伊宁进入那拉提的标准走法。", segmentIds: ["city-kok-main", "kok-burqin-main", "burqin-hemu-main", "hemu-karamay-main", "karamay-sailimu-main", "sailimu-yining-main", "yining-nalati-main"] },
      { id: "plan-nalati-alt", label: "备选 · 河谷慢行线", isMain: false, summary: "更适合白天慢游草原谷地。", segmentIds: ["city-kok-alt", "kok-burqin-alt", "burqin-hemu-alt", "hemu-karamay-alt", "karamay-sailimu-alt", "sailimu-yining-alt", "yining-nalati-alt"] },
    ],
  },
  {
    destinationId: "yining-airport",
    options: [
      { id: "plan-yining-airport-main", label: "主路线 · 完整闭环", isMain: true, summary: "按地图完整走到那拉提后返回伊宁机场。", segmentIds: ["city-kok-main", "kok-burqin-main", "burqin-hemu-main", "hemu-karamay-main", "karamay-sailimu-main", "sailimu-yining-main", "yining-nalati-main", "nalati-airport-main"] },
      { id: "plan-yining-airport-alt", label: "备选 · 慢返程", isMain: false, summary: "适合不赶时间的返机场方案。", segmentIds: ["city-kok-alt", "kok-burqin-alt", "burqin-hemu-alt", "hemu-karamay-alt", "karamay-sailimu-alt", "sailimu-yining-alt", "yining-nalati-alt", "nalati-airport-alt"] },
    ],
  },
];
